use definition in list cmd, allow to merge all defs
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

diff --git a/contribution-stats b/contribution-stats
--- a/contribution-stats
+++ b/contribution-stats
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.1 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -17,15 +17,7 @@ version_command() {
 
 # :command.usage
 contribution_stats_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "contribution-stats - Script gathering contribution stats from upstream projects\n"
-    echo
-
-  else
-    printf "contribution-stats - Script gathering contribution stats from upstream projects\n"
-    echo
-
-  fi
+  printf "contribution-stats - Script gathering contribution stats from upstream projects\n\n"
 
   printf "%s\n" "Usage:"
   printf "  contribution-stats COMMAND\n"
@@ -55,16 +47,7 @@ contribution_stats_usage() {
 
 # :command.usage
 contribution_stats_sync_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "contribution-stats sync - Clone and/or all tracked upstream repositories\n"
-    echo
-
-  else
-    printf "contribution-stats sync - Clone and/or all tracked upstream repositories\n"
-    echo
-
-  fi
-
+  printf "contribution-stats sync - Clone and/or all tracked upstream repositories\n\n"
   printf "Alias: s\n"
   echo
 
@@ -80,7 +63,7 @@ contribution_stats_sync_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--definition, -d DEFINITION (required)"
-    printf "    Definition of repositories which will be synced and the analyzed. Please\n    check repo-def directory for YAML files containing definitions. Command look\n    for all YAML files recursively under repo-def, thanks to that you can add\n    your own repo definitions.\n"
+    printf "    Definition of repositories which will be synced and then analyzed. Please\n    check repo-def directory for YAML files containing definitions. Command\n    looks for all YAML files recursively under repo-def, thanks to that you can\n    add your own repo definitions. You can also use \"all\" to merge all YAML\n    files into one.\n"
     echo
 
     # :command.usage_fixed_flags
@@ -98,16 +81,7 @@ contribution_stats_sync_usage() {
 
 # :command.usage
 contribution_stats_list_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "contribution-stats list - List contribution stats\n"
-    echo
-
-  else
-    printf "contribution-stats list - List contribution stats\n"
-    echo
-
-  fi
-
+  printf "contribution-stats list - List contribution stats\n\n"
   printf "Alias: l\n"
   echo
 
@@ -144,6 +118,11 @@ contribution_stats_list_usage() {
     printf "    Default: list.csv\n"
     echo
 
+    # :flag.usage
+    printf "  %s\n" "--definition, -d DEFINITION (required)"
+    printf "    Definition of repositories which will be synced and then analyzed. Please\n    check repo-def directory for YAML files containing definitions. Command\n    looks for all YAML files recursively under repo-def, thanks to that you can\n    add your own repo definitions. You can also use \"all\" to merge all YAML\n    files into one.\n"
+    echo
+
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
@@ -151,10 +130,12 @@ contribution_stats_list_usage() {
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  contribution-stats list\n"
+    printf "  contribution-stats list -d all\n"
+    printf "  contribution-stats list -d dasharo\n"
+    printf "  contribution-stats list -d zarhus\n"
+    printf "  contribution-stats list -d all -s 01/01/2021 -e 31/12/2022\n"
     printf "  contribution-stats list -r coreboot -s 21/02/2023\n"
     printf "  contribution-stats list -r coreboot -s 21/02/2023\n"
-    printf "  contribution-stats list -r coreboot -s 01/01/2021 -e 31/12/2022\n"
     printf "  contribution-stats list -r coreboot -s 21/02/2023 -o coreboot.csv\n"
     echo
 
@@ -164,7 +145,7 @@ contribution_stats_list_usage() {
 # :command.normalize_input
 # :command.normalize_input_function
 normalize_input() {
-  local arg flags passthru
+  local arg passthru flags
   passthru=false
 
   while [[ $# -gt 0 ]]; do
@@ -245,40 +226,6 @@ contribution_stats_sync_command() {
 
   DEFINITION="${args[--definition]}"
 
-  # Function to load repository definitions from a YAML file
-  load_repos_from_yaml() {
-        local repo_directory="repo-def"
-
-      # Check if the DEFINITION variable is set and non-empty
-      if [[ -z "$DEFINITION" ]]; then
-          echo "The DEFINITION variable is not set. Please specify a YAML file name."
-          return 1
-      fi
-
-      # Find the full path to the desired definition YAML file
-      local definition_file=$(find "$repo_directory" -type f -name "$DEFINITION.yaml" | head -n 1)
-
-      # Check if the definition file was found
-      if [[ -z "$definition_file" ]]; then
-          echo "No YAML file named $DEFINITION.yaml found in $repo_directory."
-          return 1
-      fi
-
-      # Declare the global associative array
-      declare -g -A REPOS
-
-      # Use yq to parse the YAML file and populate the REPOS array
-      # Make sure to use correct quotes and verify the command based on your yq version
-      while IFS=" " read -r key value; do
-          REPOS["$key"]="$value"
-      done < <(yq -r '. | to_entries[] | "\(.key) \(.value)"' "$definition_file")
-
-      # Optionally: Display the loaded repository URLs
-      for repo in "${!REPOS[@]}"; do
-          echo "[\"$repo\"] = \"${REPOS[$repo]}\""
-      done
-  }
-
   load_repos_from_yaml
 
   echo "Syncing repositories..."
@@ -313,6 +260,7 @@ contribution_stats_list_command() {
   END_DATE="${args[--end-date]}"
   REPO="${args[--repo]}"
   OUTPUT_FILE=$(readlink -f "${args[--out]}")
+  DEFINITION="${args[--definition]}"
 
   list_single_repo() {
       _repo="${1}"
@@ -400,7 +348,8 @@ contribution_stats_list_command() {
   rm -f "${OUTPUT_FILE}"
 
   if [ -z "${REPO}" ]; then
-      echo "Listing contributions for all tracked repositories..."
+      echo "Listing contributions for definition: ${DEFINITION}"
+      load_repos_from_yaml
       list_all_repos
   else
       echo "Listing contributions for only selected repository: ${REPO}..."
@@ -641,6 +590,20 @@ contribution_stats_list_parse_requirements() {
         fi
         ;;
 
+      # :flag.case
+      --definition | -d)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--definition']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--definition requires an argument: --definition, -d DEFINITION" >&2
+          exit 1
+        fi
+        ;;
+
       -?*)
         printf "invalid option: %s\n" "$key" >&2
         exit 1
@@ -656,6 +619,12 @@ contribution_stats_list_parse_requirements() {
 
     esac
   done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--definition']+x} ]]; then
+    printf "missing required flag: --definition, -d DEFINITION\n" >&2
+    exit 1
+  fi
 
   # :command.default_assignments
   [[ -n ${args['--start-date']:-} ]] || args['--start-date']="01/01/2013"
@@ -682,6 +651,53 @@ initialize() {
   # s,https://gitlab.com/3mdeb/\(.*\),["\1"]="https://gitlab.com/3mdeb/\1",
 
   REPOS_DIR="repos"
+
+  load_repos_from_yaml() {
+      local repo_directory="repo-def"
+
+      # Check if the DEFINITION variable is set and non-empty
+      if [[ -z "$DEFINITION" ]]; then
+          echo "The DEFINITION variable is not set. Please specify a YAML file name."
+          return 1
+      fi
+
+      # Declare the global associative array
+      declare -g -A REPOS
+
+      if [[ "$DEFINITION" == "all" ]]; then
+          # Process all YAML files in the directory
+          local yaml_files=("$repo_directory"/*.yaml)
+          if [[ ${#yaml_files[@]} -eq 0 ]]; then
+              echo "No YAML files found in $repo_directory."
+              return 1
+          fi
+
+          for file in "${yaml_files[@]}"; do
+              while IFS=" " read -r key value; do
+                  REPOS["$key"]="$value"
+              done < <(yq -r '. | to_entries[] | "\(.key) \(.value)"' "$file")
+          done
+      else
+          # Find the full path to the specified definition YAML file
+          local definition_file=$(find "$repo_directory" -type f -name "$DEFINITION.yaml" | head -n 1)
+
+          # Check if the definition file was found
+          if [[ -z "$definition_file" ]]; then
+              echo "No YAML file named $DEFINITION.yaml found in $repo_directory."
+              return 1
+          fi
+
+          # Use yq to parse the YAML file and populate the REPOS array
+          while IFS=" " read -r key value; do
+              REPOS["$key"]="$value"
+          done < <(yq -r '. | to_entries[] | "\(.key) \(.value)"' "$definition_file")
+      fi
+
+      # Optionally: Display the loaded repository URLs
+      for repo in "${!REPOS[@]}"; do
+          echo "[\"$repo\"] = \"${REPOS[$repo]}\""
+      done
+  }
 
 }
 
