initial support for repo definitions in yaml files under repo-def
Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>

diff --git a/contribution-stats b/contribution-stats
--- a/contribution-stats
+++ b/contribution-stats
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.8 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -69,13 +69,19 @@ contribution_stats_sync_usage() {
   echo
 
   printf "%s\n" "Usage:"
-  printf "  contribution-stats sync\n"
+  printf "  contribution-stats sync [OPTIONS]\n"
   printf "  contribution-stats sync --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--definition, -d DEFINITION (required)"
+    printf "    Definition of repositories which will be synced and the analyzed. Please\n    check repo-def directory for YAML files containing definitions. Command look\n    for all YAML files recursively under repo-def, thanks to that you can add\n    your own repo definitions.\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -84,7 +90,7 @@ contribution_stats_sync_usage() {
 
     # :command.usage_examples
     printf "%s\n" "Examples:"
-    printf "  contribution-stats sync\n"
+    printf "  contribution-stats sync -d dasharo\n"
     echo
 
   fi
@@ -156,12 +162,16 @@ contribution_stats_list_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -172,6 +182,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -227,6 +240,46 @@ contribution_stats_sync_command() {
   # SPDX-FileCopyrightText: 2023 3mdeb <contact@3mdeb.com>
   #
   # SPDX-License-Identifier: MIT
+
+  echo "Initialize repositories..."
+
+  DEFINITION="${args[--definition]}"
+
+  # Function to load repository definitions from a YAML file
+  load_repos_from_yaml() {
+        local repo_directory="repo-def"
+
+      # Check if the DEFINITION variable is set and non-empty
+      if [[ -z "$DEFINITION" ]]; then
+          echo "The DEFINITION variable is not set. Please specify a YAML file name."
+          return 1
+      fi
+
+      # Find the full path to the desired definition YAML file
+      local definition_file=$(find "$repo_directory" -type f -name "$DEFINITION.yaml" | head -n 1)
+
+      # Check if the definition file was found
+      if [[ -z "$definition_file" ]]; then
+          echo "No YAML file named $DEFINITION.yaml found in $repo_directory."
+          return 1
+      fi
+
+      # Declare the global associative array
+      declare -g -A REPOS
+
+      # Use yq to parse the YAML file and populate the REPOS array
+      # Make sure to use correct quotes and verify the command based on your yq version
+      while IFS=" " read -r key value; do
+          REPOS["$key"]="$value"
+      done < <(yq -r '. | to_entries[] | "\(.key) \(.value)"' "$definition_file")
+
+      # Optionally: Display the loaded repository URLs
+      for repo in "${!REPOS[@]}"; do
+          echo "[\"$repo\"] = \"${REPOS[$repo]}\""
+      done
+  }
+
+  load_repos_from_yaml
 
   echo "Syncing repositories..."
 
@@ -460,6 +513,19 @@ contribution_stats_sync_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --definition | -d)
+
+        # :flag.case_arg
+        if [[ -n ${2+x} ]]; then
+          args['--definition']="$2"
+          shift
+          shift
+        else
+          printf "%s\n" "--definition requires an argument: --definition, -d DEFINITION" >&2
+          exit 1
+        fi
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -476,6 +542,12 @@ contribution_stats_sync_parse_requirements() {
 
     esac
   done
+
+  # :command.required_flags_filter
+  if [[ -z ${args['--definition']+x} ]]; then
+    printf "missing required flag: --definition, -d DEFINITION\n" >&2
+    exit 1
+  fi
 
 }
 
@@ -600,117 +672,6 @@ initialize() {
   # vim formula for semiautomatic conversion of repositories into required format:
   # s,https://gitlab.com/3mdeb/\(.*\),["\1"]="https://gitlab.com/3mdeb/\1",
 
-  # Dasharo upstream
-  # declare -A -g REPOS=(
-  # 	["coreboot"]="https://review.coreboot.org/coreboot.git"
-  #     ["flashrom"]="https://review.coreboot.org/flashrom.git"
-  #     ["fwupd"]="https://github.com/fwupd/fwupd.git"
-  #     ["seabios"]="https://review.coreboot.org/seabios.git"
-  # )
-
-  # Zarhus upstream
-  declare -A -g REPOS=(
-  	["armbian-build"]="https://github.com/armbian/build.git"
-  	["chirpstack-gateway-os"]="https://github.com/chirpstack/chirpstack-gateway-os.git"
-  	["cukinia"]="https://github.com/savoirfairelinux/cukinia.git"
-  	["debos"]="https://github.com/go-debos/debos.git"
-  	["isar"]="https://github.com/ilbers/isar.git"
-  	["kas"]="https://github.com/siemens/kas.git"
-  	["libwpe"]="https://github.com/WebPlatformForEmbedded/libwpe.git"
-  	["linux"]="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
-  	["meta-eid"]="https://github.com/eid-project/meta-eid.git"
-  	["meta-measured"]="https://github.com/flihp/meta-measured"
-  	["meta-openembedded"]="https://github.com/openembedded/meta-openembedded.git"
-  	["meta-openwrt"]="https://github.com/kraj/meta-openwrt.git"
-  	["meta-riscv"]="https://github.com/riscv/meta-riscv.git"
-  	["meta-riscv"]="https://github.com/riscv/meta-riscv.git"
-  	["meta-security"]="https://git.yoctoproject.org/meta-security"
-  	["meta-sunxi"]="https://github.com/linux-sunxi/meta-sunxi.git"
-  	["meta-swupdate"]="https://github.com/sbabic/meta-swupdate.git"
-  	["meta-virtualization"]="git://git.yoctoproject.org/meta-virtualization"
-  	["meta-webkit"]="https://github.com/Igalia/meta-webkit.git"
-  	["poky"]="git://git.yoctoproject.org/poky"
-  	["rpi-build"]="https://github.com/notro/rpi-build.git"
-  	["swupdate"]="https://github.com/sbabic/swupdate.git"
-  	["systemd"]="https://github.com/systemd/systemd.git"
-  	["u-boot"]="https://source.denx.de/u-boot/u-boot.git"
-  )
-
-  # Zarhus own repos
-  # declare -A -g REPOS=(
-  # 	["meta-amd"]="https://github.com/3mdeb/meta-amd.git"
-  # 	["meta-balena-engine"]="https://github.com/3mdeb/meta-balena-engine.git"
-  # 	["meta-cloud-services"]="https://github.com/3mdeb/meta-cloud-services.git"
-  # 	["meta-dasharo-isar"]="git@gitlab.com:3mdeb/dasharo/meta-dasharo-isar.git"
-  # 	["meta-dts"]="https://github.com/Dasharo/meta-dts.git"
-  # 	["meta-eid"]="https://github.com/3mdeb/meta-eid.git"
-  # 	["meta-fdo"]="https://github.com/3mdeb/meta-fdo.git"
-  # 	["meta-gateworks-bsp"]="git@gitlab.com:3mdeb/trainings/meta-gateworks-bsp.git"
-  # 	["meta-imx"]="https://github.com/3mdeb/meta-imx.git"
-  # 	["meta-imx8"]="https://github.com/3mdeb/meta-imx8.git"
-  # 	["meta-influx"]="https://github.com/3mdeb/meta-influx.git"
-  # 	["meta-marvell-3mdeb"]="git@gitlab.com:3mdeb/embedded-firmware-team/meta-marvell-3mdeb.git"
-  # 	["meta-nvidia"]="https://github.com/3mdeb/meta-nvidia.git"
-  # 	["meta-ocaml"]="https://github.com/3mdeb/meta-ocaml.git"
-  # 	["meta-openembedded"]="https://github.com/3mdeb/meta-openembedded.git"
-  # 	["meta-openwrt"]="https://github.com/3mdeb/meta-openwrt.git"
-  # 	["meta-pcengines"]="https://github.com/pcengines/meta-pcengines.git"
-  # 	["meta-ppc64"]="https://github.com/3mdeb/meta-ppc64.git"
-  # 	["meta-raspberrypi"]="https://github.com/3mdeb/meta-raspberrypi.git"
-  # 	["meta-readonly-rootfs-overlay"]="https://github.com/3mdeb/meta-readonly-rootfs-overlay.git"
-  # 	["meta-riscv"]="https://github.com/3mdeb/meta-riscv.git"
-  # 	["meta-rockchip"]="https://github.com/3mdeb/meta-rockchip.git"
-  # 	["meta-rte"]="https://github.com/3mdeb/meta-rte.git"
-  # 	["meta-rust"]="https://github.com/3mdeb/meta-rust.git"
-  # 	["meta-safeboot"]="https://github.com/3mdeb/meta-safeboot.git"
-  # 	["meta-srtm"]="git@gitlab.com:3mdeb/srtm/meta-srtm.git"
-  # 	["meta-sunxi"]="https://github.com/3mdeb/meta-sunxi.git"
-  # 	["meta-tb-isar-dev"]="https://github.com/3mdeb/meta-tb-isar-dev.git"
-  # 	["meta-training"]="git@gitlab.com:3mdeb/trainings/meta-training.git"
-  # 	["meta-training-qemu"]="git@gitlab.com:3mdeb/trainings/meta-training-qemu.git"
-  # 	["meta-trenchboot"]="https://github.com/3mdeb/meta-trenchboot.git"
-  # 	["meta-trenchboot-attestation"]="https://github.com/3mdeb/meta-trenchboot-attestation.git"
-  # 	["meta-trenchboot-demo"]="https://github.com/3mdeb/meta-trenchboot-demo.git"
-  # 	["meta-vbox"]="https://github.com/3mdeb/meta-vbox.git"
-  # 	["meta-virtualization"]="https://github.com/3mdeb/meta-virtualization.git"
-  # 	["meta-zulu-java"]="https://github.com/3mdeb/meta-zulu-java.git"
-  # 	["oe-meta-go"]="https://github.com/3mdeb/oe-meta-go.git"
-  # )
-
-  # Other 3mdeb contribution
-  # declare -A -g REPOS=(
-  #     ["DPorts"]="https://github.com/DragonFlyBSD/DPorts.git"
-  #     ["DragonFlyBSD"]="https://github.com/DragonFlyBSD/DragonFlyBSD.git"
-  #     ["Octopress-LastFM-Aside"]="https://github.com/sankroh/Octopress-LastFM-Aside.git"
-  #     ["PSPTool"]="https://github.com/PSPReverse/PSPTool.git"
-  #     ["QCBOR"]="https://github.com/laurencelundblade/QCBOR.git"
-  #     ["TrenchBoot.github.io"]="https://github.com/TrenchBoot/TrenchBoot.github.io.git"
-  #     ["acpica"]="https://github.com/acpica/acpica.git"
-  #     ["ansible-role-customize-gnome"]="https://github.com/PeterMosmans/ansible-role-customize-gnome.git"
-  #     ["backends"]="https://gitlab.com/sane-project/backends.git"
-  #     ["batch2bash"]="https://github.com/gajop/batch2bash.git"
-  #     ["charra"]="https://github.com/Fraunhofer-SIT/charra.git"
-  #     ["documentation"]="https://github.com/TrenchBoot/documentation.git"
-  #     ["ec"]="https://github.com/system76/ec.git"
-  #     ["efivar"]="https://github.com/rhboot/efivar"
-  #     ["fiedka"]="https://github.com/fiedka/fiedka.git"
-  #     ["freebsd-ports"]="https://github.com/freebsd/freebsd-ports.git"
-  #     ["freebsd-src"]="https://git.FreeBSD.org/src.git"
-  #     ["homepage"]="https://review.coreboot.org/homepage.git"
-  #     ["landing-zone"]="https://github.com/TrenchBoot/landing-zone.git"
-  #     ["libwpe"]="https://github.com/WebPlatformForEmbedded/libwpe.git"
-  #     ["netbsd-pkgsrc"]="https://github.com/NetBSD/pkgsrc.git"
-  #     ["netbsd-src"]="https://github.com/NetBSD/src.git"
-  #     ["openbsd-ports"]="https://github.com/openbsd/ports.git"
-  #     ["openbsd-src"]="https://github.com/openbsd/src.git"
-  #     ["pycom-documentation"]="https://github.com/pycom/pycom-documentation.git"
-  #     ["qubes-antievilmaid"]="https://github.com/QubesOS/qubes-antievilmaid.git"
-  #     ["qubes-app-linux-split-gpg2"]="https://github.com/HW42/qubes-app-linux-split-gpg2.git"
-  #     ["qubes-builder-rpm"]="https://github.com/QubesOS/qubes-builder-rpm.git"
-  #     ["trenchboot-issues"]="https://github.com/TrenchBoot/trenchboot-issues.git"
-  #     ["xen"]="git://xenbits.xen.org/xen.git"
-  # )
-
   REPOS_DIR="repos"
 
 }
@@ -720,6 +681,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
